import type { Metadata } from "next";
import Link from 'next/link'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "서울제일한방병원",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="header">
      <img src="logo.svg" alt="Description of the image" className="header-image"/>
      <nav className="header-nav">
        <Link href="/">
          <h1 className="nav-item">입원 현황</h1>
        </Link>
        <div className="nav-divider"></div>
        <Link href="/patient">
          <h1 className="nav-item">환자 현황</h1>
        </Link>
      </nav>
    </header>
  );
}

// 푸터 컴포넌트
function Footer() {
  return (
    <footer className="footer">
      <p>Copyright &copy; {new Date().getFullYear()} 서울제일한방병원. All rights reserved.</p>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}
        <Header />
        <main className="main-content">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
